"""Describe the changes

Revision ID: 9a2fb73c2b3f
Revises: 8b8a8a508167
Create Date: 2024-12-19 15:17:52.158707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a2fb73c2b3f'
down_revision: Union[str, None] = '8b8a8a508167'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'priority')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('priority', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
